version: '3.8'

services:
  orbit-backend:
    build: .
    image: orbit_backend
    container_name: orbit_api
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis



  redis:
    image: redis:alpine
    container_name: orbit_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data: